name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install tools
      run: sudo apt-get install -y xvfb xclip xsel

    - name: Build
      run: go build

    - name: Test
      env:
        DISPLAY: ":99.0" 
      run: xvfb-run -a go test
