name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install tools
        run: sudo apt-get install -y xvfb xclip xsel

      - name: Build
        env:
          GOOS: "linux"
          GOARCH: "amd64"
        run: go build

      - name: Test
        env:
          DISPLAY: ":99.0"
        run: xvfb-run -a go testn

      - name: Create checksum
        run: sha256sum mdimg | awk '{ print $1 }' > mdimg.sha256 

      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: mdimg-linux-x64
          path: |
            mdimg
            mdimg.sha256

