name: Release

on:
  push:
    tags:
      - '*'
  permissions:
    contents: write

jobs:

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install tools
        run: sudo apt-get install -y xvfb xclip xsel

      - name: Build
        env:
          GOOS: "linux"
          GOARCH: "amd64"
        run: go build

      - name: Rename binary
        run: mv mdimg mdimg-linux-x64

      - name: Test
        env:
          DISPLAY: ":99.0"
        run: xvfb-run -a go test

      - name: Create checksum
        run: sha256sum mdimg-linux-x64 | awk '{ print $1 }' > mdimg-linux-x64.sha256 

      # - name: Upload linux build
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mdimg-linux-x64
      #     path: |
      #       mdimg-linux-x64
      #       mdimg-linux-x64.sha256

      - name: Release to github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TAG: ${{ github.ref_name }}
        run: >
          gh release create $TAG mdimg-linux-x64 mdimg-linux-x64.sha256
          --verify-tag
          --repo $OWNER/$REPO
